### ISSUE TITLE
update bin to use mqtt (for Iobroker9

### ISSUE THREAD

**Issue by metzger304** [smlight-dev/slwf01pro-firmware#1]
Hi, can you update the image, that there is an mqtt connection?
I wpuld like to use the data in iobroker...

**Comment by Tarik2142** [comment]
The problem is that for mqtt discovery, broker data must be configured
```
mqtt:
   broker: IP
   username: user
   password: user
```

Since these data are different for everyone, it is currently not possible to precompile the binary
